#!/bin/bash -l 


#!/bin/bash
#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q regular
#SBATCH --account=m77
#SBATCH -J YuP-MCGO
#SBATCH --mail-user=vandelij@mit.edu
#SBATCH --mail-type=ALL
#SBATCH -t 00:30:00

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

cd $SLURM_SUBMIT_DIR

##export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/global/cfs/cdirs/m77/pgplot.perl.intel

#run the application (Perlmutter has 128cpucores per node)
srun -n 128 -c 1 --cpu_bind=cores ./xmcgo_mpi_intel
